#!/bin/bash

HOMEDIR=~

echo "Generating public/private rsa key pair."
echo -n "Enter file in which to save the key ($HOMEDIR/.p2p/p2p_rsa): "
read FILENAME
if [[ $FILENAME =~ ^[ \t\n\r]+$ ]]; then
    echo empty
fi
